-- PR-SCORECARD-4 — OWNER-editable platform settings + Wix payment webhook.
--
-- Two responsibilities in this migration:
--
--   1. Extend the existing platform_settings table so it can host both
--      the legacy owner-approval CHANGE_PLATFORM_SETTING flow (encrypted
--      values) AND PR-SCORECARD-4's plaintext booking URLs + Wix
--      integration settings. Seeds 4 rows used by the scorecard
--      booking flow + the Wix webhook listener.
--
--   2. Create the wix_payments table that records every Wix Automation
--      webhook hit (free 15-min booking, NZD 30 Gap-Closing payment,
--      NZD 150 LIA Consultation payment, or anything else). The webhook
--      itself is shared-secret authenticated; this table is the
--      durable record of confirmed payments + bookings the staff sees
--      in /staff/wix-payments.

-- pgcrypto for gen_random_bytes() (used below to seed the
-- WIX_WEBHOOK_SECRET). IF NOT EXISTS keeps this safe to re-run on
-- environments where the extension is already installed.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─── 1. platform_settings: schema upgrade ──────────────────────────

-- Existing model: { key (PK), value, updatedAt, updatedById }.
-- New shape:      { id (PK uuid), key (unique), value, description,
--                   category, updatedById, updatedAt, createdAt }.
--
-- Strategy: add the new columns NOT NULL with defaults so any legacy
-- rows get sensible values, drop the old PK on `key`, add the new
-- uuid PK on `id`, add the unique constraint + indexes + FK.

-- 1a. Add new columns. id gets a uuid default so existing rows
--      populate themselves; description is nullable; category gets a
--      'general' default for legacy rows.
ALTER TABLE "platform_settings"
  ADD COLUMN "id"          TEXT          NOT NULL DEFAULT gen_random_uuid()::text,
  ADD COLUMN "description" TEXT,
  ADD COLUMN "category"    VARCHAR(50)   NOT NULL DEFAULT 'general',
  ADD COLUMN "createdAt"   TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 1b. Drop the old PK on `key`, add a new PK on `id`. Then add a
--      unique constraint on `key` so callers can still look up by it.
ALTER TABLE "platform_settings" DROP CONSTRAINT "platform_settings_pkey";
ALTER TABLE "platform_settings" ADD CONSTRAINT "platform_settings_pkey" PRIMARY KEY ("id");
ALTER TABLE "platform_settings"
  ADD CONSTRAINT "platform_settings_key_key" UNIQUE ("key");

-- 1c. Indexes.
CREATE INDEX "platform_settings_category_idx" ON "platform_settings"("category");

-- 1d. Forward-compat FK on updatedById. (The existing table never
--      had a declared FK on this column — adding it now keeps audit
--      attribution honest.)
ALTER TABLE "platform_settings"
  ADD CONSTRAINT "platform_settings_updatedById_fkey"
  FOREIGN KEY ("updatedById") REFERENCES "users"("id")
  ON DELETE NO ACTION ON UPDATE CASCADE;

-- 1e. Seed the 4 PR-SCORECARD-4 settings. updatedById resolves to
--      the first OWNER, else SUPER_ADMIN, else any user, so this
--      works in every environment (dev / staging / prod).
--
--      WIX_WEBHOOK_SECRET is a 64-char hex generated by pgcrypto
--      gen_random_bytes(32) inside the migration. The secret value
--      is intended to be regenerated post-migration via the OWNER
--      UI as soon as the Wix Automation is configured — the seed
--      is just so the column starts non-empty (the guard fails
--      closed when it's missing).
DO $$
DECLARE
  seed_actor_id text;
BEGIN
  SELECT id INTO seed_actor_id FROM users WHERE role = 'OWNER' LIMIT 1;
  IF seed_actor_id IS NULL THEN
    SELECT id INTO seed_actor_id FROM users WHERE role = 'SUPER_ADMIN' LIMIT 1;
  END IF;
  IF seed_actor_id IS NULL THEN
    SELECT id INTO seed_actor_id FROM users LIMIT 1;
  END IF;

  IF seed_actor_id IS NULL THEN
    -- No users yet — skip seeding. The settings will be created on
    -- first access from the OWNER UI once a user exists.
    RAISE NOTICE 'No users present; skipping PlatformSetting seed. Settings will be created on demand.';
  ELSE
    INSERT INTO "platform_settings" ("id", "key", "value", "description", "category", "updatedById", "updatedAt", "createdAt")
    VALUES
      (
        gen_random_uuid()::text,
        'BOOKING_URL_FREE_15MIN',
        'https://www.sorenavisa.com/book-free-consultation',
        'Wix Bookings URL for free 15-minute consultations (Bands 4-6 no hard stop)',
        'booking_urls',
        seed_actor_id,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
      ),
      (
        gen_random_uuid()::text,
        'BOOKING_URL_GAP_CLOSING',
        'https://www.sorenavisa.com/gap-closing-session-payment',
        'Wix payment+booking URL for the NZD 30 Gap-Closing Roadmap Session (Band 3 no hard stop)',
        'booking_urls',
        seed_actor_id,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
      ),
      (
        gen_random_uuid()::text,
        'BOOKING_URL_LIA_CONSULTATION',
        'https://www.sorenavisa.com/lia-consultation-payment',
        'Wix payment+booking URL for the NZD 150 LIA Consultation (any band with hard stop)',
        'booking_urls',
        seed_actor_id,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
      ),
      (
        gen_random_uuid()::text,
        'WIX_WEBHOOK_SECRET',
        encode(gen_random_bytes(32), 'hex'),
        'Shared secret for verifying Wix Automation webhook calls. Rotate by regenerating this value and updating the Wix Automation header.',
        'wix_integration',
        seed_actor_id,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
      )
    ON CONFLICT ("key") DO NOTHING;
  END IF;
END $$;

-- ─── 2. wix_payments + enums ────────────────────────────────────────

CREATE TYPE "WixPaymentType" AS ENUM (
  'FREE_15MIN',
  'GAP_CLOSING',
  'LIA_CONSULTATION',
  'OTHER'
);

CREATE TYPE "WixPaymentStatus" AS ENUM (
  'RECEIVED',
  'REFUNDED',
  'DISPUTED'
);

CREATE TABLE "wix_payments" (
  "id"               TEXT             NOT NULL,
  "wixPaymentId"     VARCHAR(200)     NOT NULL,
  "wixBookingId"     VARCHAR(200),
  "paymentType"      "WixPaymentType" NOT NULL,
  "amount"           DECIMAL(10, 2)   NOT NULL,
  "currency"         VARCHAR(3)       NOT NULL,
  "status"           "WixPaymentStatus" NOT NULL DEFAULT 'RECEIVED',
  "customerEmail"    VARCHAR(200)     NOT NULL,
  "customerName"     VARCHAR(200),
  "customerPhone"    VARCHAR(64),
  "bookingStart"     TIMESTAMP(3),
  "bookingEnd"       TIMESTAMP(3),
  "bookingLocation"  VARCHAR(200),
  "matchedLeadId"    TEXT,
  "matchedUserId"    TEXT,
  "rawPayload"       JSONB            NOT NULL,
  "receivedAt"       TIMESTAMP(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "wix_payments_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "wix_payments_wixPaymentId_key"
  ON "wix_payments"("wixPaymentId");

CREATE INDEX "wix_payments_customerEmail_receivedAt_idx"
  ON "wix_payments"("customerEmail", "receivedAt");
CREATE INDEX "wix_payments_matchedLeadId_idx"
  ON "wix_payments"("matchedLeadId");
CREATE INDEX "wix_payments_paymentType_receivedAt_idx"
  ON "wix_payments"("paymentType", "receivedAt");
CREATE INDEX "wix_payments_status_idx"
  ON "wix_payments"("status");

ALTER TABLE "wix_payments"
  ADD CONSTRAINT "wix_payments_matchedLeadId_fkey"
  FOREIGN KEY ("matchedLeadId") REFERENCES "leads"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "wix_payments"
  ADD CONSTRAINT "wix_payments_matchedUserId_fkey"
  FOREIGN KEY ("matchedUserId") REFERENCES "users"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
