import { Injectable } from '@nestjs/common';
import { DiscoveryService, MetadataScanner, Reflector } from '@nestjs/core';
import { PATH_METADATA, METHOD_METADATA, GUARDS_METADATA } from '@nestjs/common/constants';
import { RequestMethod } from '@nestjs/common';
import { ROLES_KEY } from '../../auth/decorators/roles.decorator';
import { STAFF_ROLES_KEY } from '../roles/staff-roles.decorator';
import { ROLE_RESPONSIBILITIES } from './role-responsibilities';

// PR-ROLES-REFERENCE — what each role can actually reach.
//
// Generated by reading the SAME metadata the guard reads at request time, over
// the controllers Nest actually registered. Not a scan of source text and not a
// hand-maintained table: a route whose @Roles changes shows the new answer on
// the next request, and a route added without @Roles shows up as ungated rather
// than quietly missing.
//
// The one thing NOT derived from code is the prose describing what a role is
// for — no decorator carries intent. That lives in role-responsibilities.ts and
// is labelled as authored, so a reader can tell which half is enforced and
// which half is a description.

export interface RouteGrant {
  method: string;
  path: string;
  controller: string;
  /** Guard classes actually applied, controller-level and handler-level. */
  guards: string[];
}

/**
 * How a route is protected. The distinction matters: "carries no @Roles" is NOT
 * the same as "anyone can call it", and reporting the two as one thing would
 * make this page cry wolf about every authenticated-but-unrestricted route
 * while hiding the genuinely open ones among them.
 */
export type RouteProtection = 'role-gated' | 'authenticated' | 'open';

export interface RoleAccess {
  role: string;
  responsibilities: string | null;
  routeCount: number;
  routes: RouteGrant[];
}

export interface RolesAccessReport {
  /** Roles seen in the UserRole enum, so a role with zero grants still appears. */
  roles: RoleAccess[];
  /** Authenticated, but restricted to no particular role — any logged-in caller. */
  authenticatedAnyRole: RouteGrant[];
  /** No authentication guard at all: webhooks, public forms, signed-token links. */
  openRoutes: RouteGrant[];
  generatedAt: string;
}

/** Guards that establish WHO the caller is. Anything else (throttling, webhook
 *  signature checks) protects a route without identifying a user. */
const AUTH_GUARDS = ['JwtAuthGuard', 'ApiKeyGuard', 'StaffRolesGuard', 'EngagementPaidGuard'];

const METHOD_NAMES: Record<number, string> = {
  [RequestMethod.GET]: 'GET',
  [RequestMethod.POST]: 'POST',
  [RequestMethod.PUT]: 'PUT',
  [RequestMethod.DELETE]: 'DELETE',
  [RequestMethod.PATCH]: 'PATCH',
  [RequestMethod.OPTIONS]: 'OPTIONS',
  [RequestMethod.HEAD]: 'HEAD',
  [RequestMethod.ALL]: 'ALL',
};

function joinPath(base: string, sub: string): string {
  const b = `/${String(base ?? '').replace(/^\/|\/$/g, '')}`;
  const s = String(sub ?? '').replace(/^\/|\/$/g, '');
  return s ? `${b}/${s}` : b;
}

@Injectable()
export class RolesAccessService {
  constructor(
    private readonly discovery: DiscoveryService,
    private readonly scanner: MetadataScanner,
    private readonly reflector: Reflector,
  ) {}

  build(knownRoles: string[]): RolesAccessReport {
    const byRole = new Map<string, RouteGrant[]>();
    const authedAny: RouteGrant[] = [];
    const open: RouteGrant[] = [];
    for (const r of knownRoles) byRole.set(r, []);

    const guardNames = (target: any): string[] =>
      (Reflect.getMetadata(GUARDS_METADATA, target) ?? [])
        .map((g: any) => (typeof g === 'function' ? g.name : g?.constructor?.name))
        .filter(Boolean);

    for (const wrapper of this.discovery.getControllers()) {
      const instance: any = wrapper.instance;
      if (!instance) continue;
      const proto = Object.getPrototypeOf(instance);
      const controllerName = wrapper.metatype?.name ?? 'Unknown';
      const basePath = Reflect.getMetadata(PATH_METADATA, wrapper.metatype ?? {}) ?? '';

      for (const methodName of this.scanner.getAllMethodNames(proto)) {
        const handler = proto[methodName];
        const httpMethod = Reflect.getMetadata(METHOD_METADATA, handler);
        if (httpMethod === undefined) continue; // not a route handler

        const guards = [
          ...guardNames(wrapper.metatype ?? {}),
          ...guardNames(handler),
        ];

        const grant: RouteGrant = {
          method: METHOD_NAMES[httpMethod] ?? String(httpMethod),
          path: joinPath(basePath, Reflect.getMetadata(PATH_METADATA, handler) ?? ''),
          controller: controllerName,
          guards,
        };

        // Same lookup order as RolesGuard: handler overrides controller.
        const roles =
          this.reflector.getAllAndOverride<string[]>(ROLES_KEY, [handler, wrapper.metatype as any]) ??
          this.reflector.getAllAndOverride<string[]>(STAFF_ROLES_KEY, [handler, wrapper.metatype as any]);

        if (!roles || roles.length === 0) {
          const identifies = guards.some((g) => AUTH_GUARDS.includes(g));
          (identifies ? authedAny : open).push(grant);
          continue;
        }
        for (const role of roles) {
          if (!byRole.has(role)) byRole.set(role, []);
          byRole.get(role)!.push(grant);
        }
      }
    }

    const sortRoutes = (a: RouteGrant, b: RouteGrant) =>
      a.path.localeCompare(b.path) || a.method.localeCompare(b.method);

    return {
      roles: [...byRole.entries()]
        .map(([role, routes]) => ({
          role,
          responsibilities: ROLE_RESPONSIBILITIES[role] ?? null,
          routeCount: routes.length,
          routes: routes.sort(sortRoutes),
        }))
        .sort((a, b) => b.routeCount - a.routeCount || a.role.localeCompare(b.role)),
      authenticatedAnyRole: authedAny.sort(sortRoutes),
      openRoutes: open.sort(sortRoutes),
      generatedAt: new Date().toISOString(),
    };
  }
}
